version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-reading-laravel
    volumes:
      - ./src:/var/www
    ports:
      - "8000:8000"
      - "80:80"
    networks:
      - music-reading
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=music-reading
      - DB_USERNAME=root
      - DB_PASSWORD=secret

  db:
    image: mysql:8.0
    container_name: music-reading-db
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: music-reading
      MYSQL_USER: music-reading-admin
      MYSQL_PASSWORD: secret
    networks:
      - music-reading
      
  nginx:
    image: nginx:latest
    container_name: music-reading-nginx
    volumes:
      - ./src:/var/www
      - ./configs/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "8000:8000"
    depends_on:
      - webapp
    networks:
      - music-reading

networks:
  music-reading:
    driver: bridge